releasetasks:
  plugins:
    - log_collect
    - ses
  emails:
    - release-automation-notifications@mozilla.com

release-drivers:
  plugins:
    - ses
  emails:
    # release-drivers@m.o is not used anymore for automation emails (bug 1407265)
    - release-signoff@mozilla.org

release-drivers-staging:
  plugins:
    - ses
  emails:
    - release+tcstaging@mozilla.com
